# -*- coding: utf-8 -*-
"""perturbations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aADpqAPzaUmO3o7vKZ-aYy02tguMORFM

# Setup
"""

#Pray for P100
!nvidia-smi

#Clone project repo
import os
from getpass import getpass
import urllib

user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # your password is converted into url format
repo_name = input('Repo name: ')

cmd_string = 'git clone --recurse-submodules https://{0}:{1}@github.com/{0}/{2}.git'.format(user, password, repo_name)

os.system(cmd_string)
cmd_string, password = "", "" # removing the password from the variable

!python -m spacy download en

cd ParlAI/

!python setup.py develop

!pip install torch==1.1.0 torchvision==0.3.0

!sh run.sh train s2s_att_general personachat 3

!sh run.sh perturb s2s_att_general personachat 3